kotlin_library(
    name = "6",
    srcs = glob(["*.kt"]),
    tests = [
        "//test/i_introduction/_6_Data_Classes:6",
    ],
    deps = [
        ":java",
        "//src/util:util-kotlin",
    ],
    visibility = ["PUBLIC"],
)

java_library(
    name = "java",
    srcs = glob(["*.java"]),
    deps = [
        "//src/util:util-java",
    ],
    exported_deps = [
        "//src/util:util-java",
    ],
    visibility = [
        "//src/i_introduction/_6_Data_Classes:6",
    ]
)
