kotlin_library(
    name = "3",
    srcs = glob(["*.kt"]),
    tests = [
        "//test/i_introduction/_3_Default_Arguments:3",
    ],
    deps = [
        ":java",
        "//src/util:util-kotlin",
    ],
    visibility = ["PUBLIC"],
)


java_library(
    name = "java",
    srcs = glob(["*.java"]),
    deps = [
        "//src/util:util-java",
    ],
    exported_deps = [
        "//src/util:util-java",
    ],
    visibility = [
        "//src/i_introduction/_3_Default_Arguments:3",
    ]
)