kotlin_test(
    name = "3",
    srcs = glob(["*.kt"]),
    deps = [
        "//src/i_introduction/_3_Default_Arguments:3",
        "//lib:junit",
        "//lib/kotlin:kotlin-stdlib",
    ],
    visibility = ["PUBLIC"],
)